# -*- coding: utf-8 -*-
"""Traducao do texto que vem de dentro do SQL, por vertical e por idioma.

    GLOSSARIO[vertical][lang] -> [(de, para), ...]

O catalogo de 292 arquivos T-SQL devolve nome de coluna ('GGR', 'Turnover',
'Var % GGR') e valor de celula ('Internal Traffic', 'InfluenciadoresZephyr') em
vocabulario de apostas e em ingles — e ele nao pode ser alterado: e a parte densa
do projeto e duplicar por vertical ou por idioma dobraria a manutencao. A
substituicao acontece na saida, em `vertical.traduz()`.

A ORDEM importa e as listas nao sao dicts por isso: o mais especifico vem
primeiro, senao 'GGR' come o 'Hold (NGR/GGR)' e 'FTD' come o 'FTD_Percent'.

`bet`/`pt` e vazia de proposito — nessa combinacao o texto do SQL ja esta no
vocabulario certo, e a funcao devolve o proprio objeto sem custo.
"""

GLOSSARIO = {
    "bet": {
        "pt": [],
        "es":
        [('Operational Overview', 'Visión operativa'),
         ('Acquisition - All', 'Adquisición - Todos'),
         ('Acquisition', 'Adquisición'),
         ('Global GGR', 'GGR global'),
         ('Global Turnover', 'Turnover global'),
         ('Margin', 'Margen'),
         ('Cost', 'Coste'),
         ('Unique Gamblers MTD', 'Jugadores únicos MTD'),
         ('Unique Gamblers', 'Jugadores únicos'),
         ('Unique MTD', 'Únicos MTD'),
         ('Gamblers Casino', 'Jugadores Casino'),
         ('Gamblers Sports', 'Jugadores Deportes'),
         ('Gamblers (Daily AVG)', 'Jugadores (media diaria)'),
         ('Gamblers', 'Jugadores'),
         ('Active Players', 'Jugadores activos'),
         ('Retention Rate', 'Retención'),
         ('Reactivations Rate', 'Tasa de reactivación'),
         ('Reactivations', 'Reactivaciones'),
         ('Reativations', 'Reactivaciones'),
         ('AVG Bet', 'Apuesta media'),
         ('Avg bet', 'Apuesta media'),
         ('Generosity', 'Bonos'),
         ('Online Marketing', 'Medios online'),
         ('Internal Traffic', 'Tráfico interno'),
         ('External Traffic', 'Tráfico externo'),
         ('Grand Total', 'Total general'),
         ('Top 5 Btags', 'Top 5 campañas'),
         ('Affiliate_Manager', 'Gerente_Afiliado'),
         ('Affiliate_Name', 'Afiliado'),
         ('Affiliate_Id', 'Afiliado_Id'),
         ('Deposits', 'Depósitos'),
         ('Withdrawals', 'Retiros'),
         ('withdrawals', 'Retiros'),
         ('Registrations', 'Registros'),
         ('Registration', 'Registros'),
         ('Investiment', 'Inversión'),
         ('Btags', 'Campañas'),
         ('btag', 'campaña'),
         ('Bonus', 'Bonos'),
         ('Sportsbook', 'Deportes'),
         ('Sports', 'Deportes'),
         ('Affiliates', 'Afiliados'),
         ('Affiliate', 'Afiliado'),
         ('Organic', 'Orgánico'),
         ('Others', 'Otros')],
        "en":
        [('Reativations', 'Reactivations'), ('Investiment', 'Investment')],
    },
    "ecommerce": {
        "pt":
        [('Hold (NGR/GGR)', 'Margem líquida'),
         ('Operational Overview', 'Visão operacional'),
         ('Acquisition - All', 'Aquisição - Todos'),
         ('Acquisition', 'Aquisição'),
         ('Global GGR', 'Receita global'),
         ('Global Turnover', 'GMV global'),
         ('Margin', 'Take rate'),
         ('Total_Dep', 'Total_Pgto'),
         ('Avg_Dep', 'Avg_Pgto'),
         ('Var % Dep', 'Var % Pgto'),
         ('Cost', 'Custo'),
         ('NARPU/Unique', 'Margem/cliente'),
         ('ARPU/Unique', 'Receita/cliente'),
         ('TOAU/Unique', 'GMV/cliente'),
         ('NGR/DEP', 'Margem/pagamento'),
         ('Unique Gamblers MTD', 'Clientes únicos MTD'),
         ('Unique Gamblers', 'Clientes únicos'),
         ('Unique MTD', 'Únicos MTD'),
         ('Gamblers Casino', 'Clientes Marketplace'),
         ('Gamblers Sports', 'Clientes Loja própria'),
         ('Gamblers (Daily AVG)', 'Clientes (média diária)'),
         ('Gamblers', 'Clientes'),
         ('Active Players', 'Clientes ativos'),
         ('Retention Rate', 'Retenção'),
         ('Reactivations Rate', 'Taxa de reativação'),
         ('Reactivations', 'Reativações'),
         ('Reativations', 'Reativações'),
         ('AVG Bet', 'Ticket médio'),
         ('Avg bet', 'Ticket médio'),
         ('Generosity', 'Descontos'),
         ('Online Marketing', 'Mídia online'),
         ('Internal Traffic', 'Tráfego interno'),
         ('External Traffic', 'Tráfego externo'),
         ('Grand Total', 'Total geral'),
         ('Top 5 Btags', 'Top 5 campanhas'),
         ('FTDs Top 5', '1ª compra Top 5'),
         ('InfluenciadoresZephyr', 'InfluenciadoresNordika'),
         ('InfluenciadoresQuasar', 'InfluenciadoresVellora'),
         ('InfluenciadoresLumen', 'InfluenciadoresCintra'),
         ('FTD_Percent', 'Novos_Percent'),
         ('FTD_QTD', 'Novos_QTD'),
         ('FTD_Date', 'Data_1a_Compra'),
         ('Affiliate_Manager', 'Gerente_Parceria'),
         ('Affiliate_Name', 'Parceiro'),
         ('Affiliate_Id', 'Parceiro_Id'),
         ('FTDs', 'Novos clientes'),
         ('FTD', '1ª compra'),
         ('Turnover', 'GMV'),
         ('Netcash', 'Receita líquida'),
         ('Deposits', 'Pagamentos'),
         ('Withdrawals', 'Reembolsos'),
         ('withdrawals', 'Reembolsos'),
         ('Registrations', 'Cadastros'),
         ('Registration', 'Cadastros'),
         ('Registros', 'Cadastros'),
         ('Investiment', 'Investimento'),
         ('CPA', 'CAC'),
         ('Btags', 'Campanhas'),
         ('btag', 'campanha'),
         ('Bonus', 'Cupons'),
         ('NGR', 'Margem contrib.'),
         ('GGR', 'Receita'),
         ('Sportsbook', 'Loja própria'),
         ('Sports', 'Loja própria'),
         ('Casino', 'Marketplace'),
         ('Affiliates', 'Parceiros'),
         ('Afiliados', 'Parceiros'),
         ('Affiliate', 'Parceiro'),
         ('Influencers', 'Influenciadores'),
         ('Organic', 'Orgânico'),
         ('Others', 'Outros')],
        "es":
        [('Hold (NGR/GGR)', 'Margen neto'),
         ('Operational Overview', 'Visión operativa'),
         ('Acquisition - All', 'Adquisición - Todos'),
         ('Acquisition', 'Adquisición'),
         ('Global GGR', 'Ingresos globales'),
         ('Global Turnover', 'GMV global'),
         ('Margin', 'Take rate'),
         ('Total_Dep', 'Total_Pago'),
         ('Avg_Dep', 'Prom_Pago'),
         ('Var % Dep', 'Var % Pago'),
         ('Cost', 'Coste'),
         ('NARPU/Unique', 'Margen/cliente'),
         ('ARPU/Unique', 'Ingresos/cliente'),
         ('TOAU/Unique', 'GMV/cliente'),
         ('NGR/DEP', 'Margen/pago'),
         ('Unique Gamblers MTD', 'Clientes únicos MTD'),
         ('Unique Gamblers', 'Clientes únicos'),
         ('Unique MTD', 'Únicos MTD'),
         ('Gamblers Casino', 'Clientes Marketplace'),
         ('Gamblers Sports', 'Clientes Tienda propia'),
         ('Gamblers (Daily AVG)', 'Clientes (media diaria)'),
         ('Gamblers', 'Clientes'),
         ('Active Players', 'Clientes activos'),
         ('Retention Rate', 'Retención'),
         ('Reactivations Rate', 'Tasa de reactivación'),
         ('Reactivations', 'Reactivaciones'),
         ('Reativations', 'Reactivaciones'),
         ('AVG Bet', 'Ticket medio'),
         ('Avg bet', 'Ticket medio'),
         ('Generosity', 'Descuentos'),
         ('Online Marketing', 'Medios online'),
         ('Internal Traffic', 'Tráfico interno'),
         ('External Traffic', 'Tráfico externo'),
         ('Grand Total', 'Total general'),
         ('Top 5 Btags', 'Top 5 campañas'),
         ('FTDs Top 5', '1ª compra Top 5'),
         ('InfluencersZephyr', 'InfluencersNordika'),
         ('InfluencersQuasar', 'InfluencersVellora'),
         ('InfluencersLumen', 'InfluencersCintra'),
         ('InfluenciadoresZephyr', 'InfluencersNordika'),
         ('InfluenciadoresQuasar', 'InfluencersVellora'),
         ('InfluenciadoresLumen', 'InfluencersCintra'),
         ('FTD_Percent', 'Nuevos_Percent'),
         ('FTD_QTD', 'Nuevos_QTD'),
         ('FTD_Date', 'Fecha_1a_Compra'),
         ('Affiliate_Manager', 'Gerente_Alianza'),
         ('Affiliate_Name', 'Socio'),
         ('Affiliate_Id', 'Socio_Id'),
         ('FTDs', 'Clientes nuevos'),
         ('FTD', '1ª compra'),
         ('Turnover', 'GMV'),
         ('Netcash', 'Ingresos netos'),
         ('Deposits', 'Pagos'),
         ('Withdrawals', 'Reembolsos'),
         ('withdrawals', 'Reembolsos'),
         ('Registrations', 'Registros'),
         ('Registration', 'Registros'),
         ('Investiment', 'Inversión'),
         ('CPA', 'CAC'),
         ('Btags', 'Campañas'),
         ('btag', 'campaña'),
         ('Bonus', 'Cupones'),
         ('NGR', 'Margen contrib.'),
         ('GGR', 'Ingresos'),
         ('Sportsbook', 'Tienda propia'),
         ('Sports', 'Tienda propia'),
         ('Casino', 'Marketplace'),
         ('Affiliates', 'Socios'),
         ('Afiliados', 'Socios'),
         ('Affiliate', 'Socio'),
         ('Influencers', 'Influencers'),
         ('Organic', 'Orgánico'),
         ('Others', 'Otros')],
        "en":
        [('Hold (NGR/GGR)', 'Net margin'),
         ('Acquisition - All', 'Acquisition - All'),
         ('Global GGR', 'Global revenue'),
         ('Global Turnover', 'Global GMV'),
         ('Margin', 'Take rate'),
         ('Total_Dep', 'Total_Pmt'),
         ('Avg_Dep', 'Avg_Pmt'),
         ('Var % Dep', 'Var % Pmt'),
         ('NARPU/Unique', 'Margin/customer'),
         ('ARPU/Unique', 'Revenue/customer'),
         ('TOAU/Unique', 'GMV/customer'),
         ('NGR/DEP', 'Margin/payment'),
         ('Unique Gamblers MTD', 'Unique customers MTD'),
         ('Unique Gamblers', 'Unique customers'),
         ('Gamblers Casino', 'Marketplace customers'),
         ('Gamblers Sports', 'Own store customers'),
         ('Gamblers (Daily AVG)', 'Customers (daily avg)'),
         ('Gamblers', 'Customers'),
         ('Active Players', 'Active customers'),
         ('Retention Rate', 'Retention'),
         ('Reactivations Rate', 'Reactivation rate'),
         ('Reactivations', 'Reactivations'),
         ('Reativations', 'Reactivations'),
         ('AVG Bet', 'Avg ticket'),
         ('Avg bet', 'Avg ticket'),
         ('Generosity', 'Discounts'),
         ('Online Marketing', 'Online media'),
         ('Top 5 Btags', 'Top 5 campaigns'),
         ('FTDs Top 5', 'First purchase Top 5'),
         ('InfluencersZephyr', 'InfluencersNordika'),
         ('InfluencersQuasar', 'InfluencersVellora'),
         ('InfluencersLumen', 'InfluencersCintra'),
         ('InfluenciadoresZephyr', 'InfluencersNordika'),
         ('InfluenciadoresQuasar', 'InfluencersVellora'),
         ('InfluenciadoresLumen', 'InfluencersCintra'),
         ('FTD_Percent', 'New_Percent'),
         ('FTD_QTD', 'New_QTD'),
         ('FTD_Date', 'First_Purchase_Date'),
         ('Affiliate_Manager', 'Partner_Manager'),
         ('Affiliate_Name', 'Partner'),
         ('Affiliate_Id', 'Partner_Id'),
         ('FTDs', 'New customers'),
         ('FTD', 'First purchase'),
         ('Turnover', 'GMV'),
         ('Netcash', 'Net revenue'),
         ('Deposits', 'Payments'),
         ('Withdrawals', 'Refunds'),
         ('withdrawals', 'Refunds'),
         ('Registrations', 'Sign-ups'),
         ('Registration', 'Sign-ups'),
         ('Registros', 'Sign-ups'),
         ('Investiment', 'Investment'),
         ('CPA', 'CAC'),
         ('Btags', 'Campaigns'),
         ('btag', 'campaign'),
         ('Bonus', 'Coupons'),
         ('NGR', 'Contrib. margin'),
         ('GGR', 'Revenue'),
         ('Sportsbook', 'Own store'),
         ('Sports', 'Own store'),
         ('Casino', 'Marketplace'),
         ('Affiliates', 'Partners'),
         ('Afiliados', 'Partners'),
         ('Affiliate', 'Partner')],
    },
}
