# -*- coding: utf-8 -*-
"""Vocabulario de negocio por vertical e por idioma.

    TERMOS[vertical][lang][chave] -> texto na tela

Duas dimensoes, dois motivos diferentes:

  * **vertical** (`bet` / `ecommerce`) troca o *conceito*: a mesma coluna do
    warehouse e "GGR" numa operacao de apostas e "Receita" num e-commerce.
  * **idioma** (`pt` / `es` / `en`) traduz o mesmo conceito.

Os seis blocos tem exatamente as mesmas chaves — `vertical.py` confere isso no
import, porque chave faltando aqui viraria KeyError na tela e nao no deploy.

`{m}` nos rotulos de eixo do cohort e o nome da metrica, injetado em runtime.

O bloco `pt` e a redacao original do projeto; `es` e `en` sairam dela, mantendo
os termos de mercado que nao se traduzem (GGR, NGR, GMV, take rate, netcash,
seller, marketplace).
"""

TERMOS = {
    "bet": {
        "pt":
        {'vertical_nome': 'Apostas',
         'unidade_cliente': 'jogador',
         'unidade_cliente_plural': 'jogadores',
         'vertical_a': 'Casino',
         'vertical_b': 'Sportsbook',
         'vertical_par': 'casino + sportsbook',
         'ggr': 'GGR',
         'ggr_hint': 'Casino + Sportsbook no período.',
         'ngr': 'NGR',
         'ngr_hint': 'GGR menos bônus e custos, como gravado na base.',
         'turnover': 'Turnover',
         'turnover_hint': 'Volume apostado.',
         'margem': 'Margem',
         'margem_hint': 'GGR / Turnover.',
         'hold': 'Hold',
         'hold_hint': 'NGR / GGR.',
         'depositos': 'Depósitos',
         'depositos_hint': 'Somente pagamentos com Status = Completed.',
         'saques': 'Saques',
         'saques_hint': 'Somente pagamentos com Status = Completed.',
         'netcash': 'Netcash',
         'netcash_hint': 'Depósitos menos saques.',
         'ftds': 'FTDs',
         'ftds_hint': 'Jogadores com primeiro depósito no período.',
         'registros': 'Registros',
         'registros_hint': 'Cadastros criados no período.',
         'uap': 'Jogadores ativos',
         'uap_hint': 'Únicos com aposta em casino ou sports.',
         'arpu': 'ARPU',
         'arpu_hint': 'GGR por jogador ativo.',
         'itens': 'Apostas',
         'donut_vertical': 'Receita por vertical',
         'donut_vertical_desc': 'GGR de casino contra sportsbook no período.',
         'donut_provedor': 'Receita por provedor',
         'donut_provedor_desc': 'Top 12 provedores de casino por GGR; o restante soma em '
                                '“Outros”.',
         'donut_canal': 'Aquisição por canal',
         'donut_canal_desc': 'Canal de cadastro do jogador; as métricas são do período '
                             'selecionado.',
         'nota_ngr_zero': 'O NGR do sportsbook vem zerado nesta base — “NGR” e “Hold” '
                          'refletem apenas o casino.',
         'overview_desc': 'GGR, NGR, depósitos e aquisição do período, com comparação contra '
                          'a janela anterior de mesma duração.',
         'retention_desc': 'Retenção de cohorts por GGR, Turnover, Deposits e Netcash.',
         'report_master_desc': 'Réplica da planilha do bot: 5 abas (Operational Overview, '
                               'Casino, Sports, CRM e Acquisition) com as métricas do '
                               'período. 76 consultas — leva vários minutos.',
         'monitoring_desc': 'Performance por gerente de afiliados, comparando dois períodos.',
         'bpa_desc': 'Aquisição: FTDs, depósitos e GGR por canal, dois períodos.',
         'bpd_desc': 'Distribuição de FTDs e receita por canal de aquisição.',
         'bpa_merge_nome': 'Aquisição por canal',
         'cohort_eixo_total': '{m} (k)',
         'cohort_eixo_medio': '{m} médio por jogador ativo (R$)',
         'cohort_eixo_acum': '{m} médio acumulado por jogador (R$)',
         'cohort_variant_avg': 'Média por jogador',
         'cohort_variant_avg_hint': 'Soma da safra dividida pelos jogadores ativos daquele '
                                    'mês.',
         'cohort_metric_deposits': 'Deposits',
         'cohort_metric_netcash': 'Netcash'},
        "es":
        {'vertical_nome': 'Apuestas',
         'unidade_cliente': 'jugador',
         'unidade_cliente_plural': 'jugadores',
         'vertical_a': 'Casino',
         'vertical_b': 'Deportes',
         'vertical_par': 'casino + deportes',
         'ggr': 'GGR',
         'ggr_hint': 'Casino + Deportes en el período.',
         'ngr': 'NGR',
         'ngr_hint': 'GGR menos bonos y costes, tal como está registrado en la base.',
         'turnover': 'Turnover',
         'turnover_hint': 'Volumen apostado.',
         'margem': 'Margen',
         'margem_hint': 'GGR / Turnover.',
         'hold': 'Hold',
         'hold_hint': 'NGR / GGR.',
         'depositos': 'Depósitos',
         'depositos_hint': 'Solo pagos con Status = Completed.',
         'saques': 'Retiros',
         'saques_hint': 'Solo pagos con Status = Completed.',
         'netcash': 'Netcash',
         'netcash_hint': 'Depósitos menos retiros.',
         'ftds': 'FTDs',
         'ftds_hint': 'Jugadores con su primer depósito en el período.',
         'registros': 'Registros',
         'registros_hint': 'Cuentas creadas en el período.',
         'uap': 'Jugadores activos',
         'uap_hint': 'Únicos con apuesta en casino o deportes.',
         'arpu': 'ARPU',
         'arpu_hint': 'GGR por jugador activo.',
         'itens': 'Apuestas',
         'donut_vertical': 'Ingresos por vertical',
         'donut_vertical_desc': 'GGR de casino frente a deportes en el período.',
         'donut_provedor': 'Ingresos por proveedor',
         'donut_provedor_desc': 'Top 12 proveedores de casino por GGR; el resto suma en '
                                '“Otros”.',
         'donut_canal': 'Adquisición por canal',
         'donut_canal_desc': 'Canal de registro del jugador; las métricas son del período '
                             'seleccionado.',
         'nota_ngr_zero': 'El NGR de deportes viene en cero en esta base — “NGR” y “Hold” '
                          'reflejan solo el casino.',
         'overview_desc': 'GGR, NGR, depósitos y adquisición del período, comparados con la '
                          'ventana anterior de igual duración.',
         'retention_desc': 'Retención de cohortes por GGR, Turnover, Depósitos y Netcash.',
         'report_master_desc': 'Réplica de la planilla del bot: 5 hojas (Operational '
                               'Overview, Casino, Deportes, CRM y Adquisición) con las '
                               'métricas del período. 76 consultas — tarda varios minutos.',
         'monitoring_desc': 'Rendimiento por gerente de afiliados, comparando dos períodos.',
         'bpa_desc': 'Adquisición: FTDs, depósitos e ingresos por canal, dos períodos.',
         'bpd_desc': 'Distribución de FTDs e ingresos por canal de adquisición.',
         'bpa_merge_nome': 'Adquisición por canal',
         'cohort_eixo_total': '{m} (k)',
         'cohort_eixo_medio': '{m} medio por jugador activo (R$)',
         'cohort_eixo_acum': '{m} medio acumulado por jugador (R$)',
         'cohort_variant_avg': 'Media por jugador',
         'cohort_variant_avg_hint': 'Total de la cohorte dividido por los jugadores activos '
                                    'de ese mes.',
         'cohort_metric_deposits': 'Depósitos',
         'cohort_metric_netcash': 'Netcash'},
        "en":
        {'vertical_nome': 'Betting',
         'unidade_cliente': 'player',
         'unidade_cliente_plural': 'players',
         'vertical_a': 'Casino',
         'vertical_b': 'Sportsbook',
         'vertical_par': 'casino + sportsbook',
         'ggr': 'GGR',
         'ggr_hint': 'Casino + Sportsbook in the period.',
         'ngr': 'NGR',
         'ngr_hint': 'GGR minus bonuses and costs, as recorded in the database.',
         'turnover': 'Turnover',
         'turnover_hint': 'Amount wagered.',
         'margem': 'Margin',
         'margem_hint': 'GGR / Turnover.',
         'hold': 'Hold',
         'hold_hint': 'NGR / GGR.',
         'depositos': 'Deposits',
         'depositos_hint': 'Only payments with Status = Completed.',
         'saques': 'Withdrawals',
         'saques_hint': 'Only payments with Status = Completed.',
         'netcash': 'Netcash',
         'netcash_hint': 'Deposits minus withdrawals.',
         'ftds': 'FTDs',
         'ftds_hint': 'Players with their first deposit in the period.',
         'registros': 'Registrations',
         'registros_hint': 'Accounts created in the period.',
         'uap': 'Active players',
         'uap_hint': 'Unique players with a bet in casino or sports.',
         'arpu': 'ARPU',
         'arpu_hint': 'GGR per active player.',
         'itens': 'Bets',
         'donut_vertical': 'Revenue by vertical',
         'donut_vertical_desc': 'Casino GGR against sportsbook in the period.',
         'donut_provedor': 'Revenue by provider',
         'donut_provedor_desc': 'Top 12 casino providers by GGR; the rest add up under '
                                '“Others”.',
         'donut_canal': 'Acquisition by channel',
         'donut_canal_desc': 'Player sign-up channel; the metrics are from the selected '
                             'period.',
         'nota_ngr_zero': 'Sportsbook NGR comes in as zero in this database — “NGR” and '
                          '“Hold” reflect the casino only.',
         'overview_desc': 'GGR, NGR, deposits and acquisition for the period, compared '
                          'against the previous window of the same length.',
         'retention_desc': 'Cohort retention by GGR, Turnover, Deposits and Netcash.',
         'report_master_desc': 'Replica of the bot spreadsheet: 5 tabs (Operational '
                               'Overview, Casino, Sports, CRM and Acquisition) with the '
                               'period metrics. 76 queries — takes several minutes.',
         'monitoring_desc': 'Performance by affiliate manager, comparing two periods.',
         'bpa_desc': 'Acquisition: FTDs, deposits and GGR by channel, two periods.',
         'bpd_desc': 'Distribution of FTDs and revenue by acquisition channel.',
         'bpa_merge_nome': 'Acquisition by channel',
         'cohort_eixo_total': '{m} (k)',
         'cohort_eixo_medio': '{m} per active player (R$)',
         'cohort_eixo_acum': 'Cumulative {m} per player (R$)',
         'cohort_variant_avg': 'Average per player',
         'cohort_variant_avg_hint': 'Cohort total divided by the players active that month.',
         'cohort_metric_deposits': 'Deposits',
         'cohort_metric_netcash': 'Netcash'},
    },
    "ecommerce": {
        "pt":
        {'vertical_nome': 'E-commerce',
         'unidade_cliente': 'cliente',
         'unidade_cliente_plural': 'clientes',
         'vertical_a': 'Marketplace (3P)',
         'vertical_b': 'Loja própria (1P)',
         'vertical_par': 'marketplace + loja própria',
         'ggr': 'Receita',
         'ggr_hint': 'Comissão do marketplace (3P) + margem bruta da loja própria (1P).',
         'ngr': 'Margem de contribuição',
         'ngr_hint': 'Receita menos cupons e descontos concedidos.',
         'turnover': 'GMV',
         'turnover_hint': 'Valor total transacionado nos pedidos.',
         'margem': 'Take rate',
         'margem_hint': 'Receita / GMV.',
         'hold': 'Margem líquida',
         'hold_hint': 'Margem de contribuição / Receita.',
         'depositos': 'Pagamentos aprovados',
         'depositos_hint': 'Somente transações com Status = Completed.',
         'saques': 'Reembolsos',
         'saques_hint': 'Somente transações com Status = Completed.',
         'netcash': 'Receita líquida',
         'netcash_hint': 'Pagamentos aprovados menos reembolsos.',
         'ftds': 'Novos clientes',
         'ftds_hint': 'Clientes com a primeira compra no período.',
         'registros': 'Cadastros',
         'registros_hint': 'Contas criadas no período.',
         'uap': 'Clientes ativos',
         'uap_hint': 'Únicos com pedido no marketplace ou na loja própria.',
         'arpu': 'Receita por cliente',
         'arpu_hint': 'Receita dividida pelos clientes ativos.',
         'itens': 'Itens',
         'donut_vertical': 'Receita por operação',
         'donut_vertical_desc': 'Marketplace (3P) contra loja própria (1P) no período.',
         'donut_provedor': 'Receita por seller',
         'donut_provedor_desc': 'Top 12 sellers por receita; o restante soma em “Outros”.',
         'donut_canal': 'Aquisição por canal',
         'donut_canal_desc': 'Canal de cadastro do cliente; as métricas são do período '
                             'selecionado.',
         'nota_ngr_zero': 'A margem da loja própria vem zerada nesta base — “Margem de '
                          'contribuição” e “Margem líquida” refletem apenas o marketplace.',
         'overview_desc': 'Receita, margem, pagamentos e aquisição do período, com '
                          'comparação contra a janela anterior de mesma duração.',
         'retention_desc': 'Retenção de cohorts por Receita, GMV, Pagamentos e Receita '
                           'líquida.',
         'report_master_desc': 'Planilha executiva: 5 abas (Operational Overview, '
                               'Marketplace, Loja própria, CRM e Aquisição) com as métricas '
                               'do período. 76 consultas.',
         'monitoring_desc': 'Performance por gerente de parcerias, comparando dois períodos.',
         'bpa_desc': 'Aquisição: novos clientes, pagamentos e receita por canal, dois '
                     'períodos.',
         'bpd_desc': 'Distribuição de novos clientes e receita por canal de aquisição.',
         'bpa_merge_nome': 'Aquisição por canal',
         'cohort_eixo_total': '{m} (k)',
         'cohort_eixo_medio': '{m} médio por cliente ativo (R$)',
         'cohort_eixo_acum': '{m} médio acumulado por cliente (R$)',
         'cohort_variant_avg': 'Média por cliente',
         'cohort_variant_avg_hint': 'Soma da safra dividida pelos clientes ativos daquele '
                                    'mês.',
         'cohort_metric_deposits': 'Pagamentos',
         'cohort_metric_netcash': 'Receita líquida'},
        "es":
        {'vertical_nome': 'E-commerce',
         'unidade_cliente': 'cliente',
         'unidade_cliente_plural': 'clientes',
         'vertical_a': 'Marketplace (3P)',
         'vertical_b': 'Tienda propia (1P)',
         'vertical_par': 'marketplace + tienda propia',
         'ggr': 'Ingresos',
         'ggr_hint': 'Comisión del marketplace (3P) + margen bruto de la tienda propia (1P).',
         'ngr': 'Margen de contribución',
         'ngr_hint': 'Ingresos menos cupones y descuentos concedidos.',
         'turnover': 'GMV',
         'turnover_hint': 'Valor total transaccionado en los pedidos.',
         'margem': 'Take rate',
         'margem_hint': 'Ingresos / GMV.',
         'hold': 'Margen neto',
         'hold_hint': 'Margen de contribución / Ingresos.',
         'depositos': 'Pagos aprobados',
         'depositos_hint': 'Solo transacciones con Status = Completed.',
         'saques': 'Reembolsos',
         'saques_hint': 'Solo transacciones con Status = Completed.',
         'netcash': 'Ingresos netos',
         'netcash_hint': 'Pagos aprobados menos reembolsos.',
         'ftds': 'Clientes nuevos',
         'ftds_hint': 'Clientes con su primera compra en el período.',
         'registros': 'Registros',
         'registros_hint': 'Cuentas creadas en el período.',
         'uap': 'Clientes activos',
         'uap_hint': 'Únicos con pedido en el marketplace o en la tienda propia.',
         'arpu': 'Ingresos por cliente',
         'arpu_hint': 'Ingresos divididos por los clientes activos.',
         'itens': 'Ítems',
         'donut_vertical': 'Ingresos por operación',
         'donut_vertical_desc': 'Marketplace (3P) frente a tienda propia (1P) en el período.',
         'donut_provedor': 'Ingresos por seller',
         'donut_provedor_desc': 'Top 12 sellers por ingresos; el resto suma en “Otros”.',
         'donut_canal': 'Adquisición por canal',
         'donut_canal_desc': 'Canal de registro del cliente; las métricas son del período '
                             'seleccionado.',
         'nota_ngr_zero': 'El margen de la tienda propia viene en cero en esta base — '
                          '“Margen de contribución” y “Margen neto” reflejan solo el '
                          'marketplace.',
         'overview_desc': 'Ingresos, margen, pagos y adquisición del período, comparados con '
                          'la ventana anterior de igual duración.',
         'retention_desc': 'Retención de cohortes por Ingresos, GMV, Pagos e Ingresos netos.',
         'report_master_desc': 'Planilla ejecutiva: 5 hojas (Operational Overview, '
                               'Marketplace, Tienda propia, CRM y Adquisición) con las '
                               'métricas del período. 76 consultas.',
         'monitoring_desc': 'Rendimiento por gerente de alianzas, comparando dos períodos.',
         'bpa_desc': 'Adquisición: clientes nuevos, pagos e ingresos por canal, dos '
                     'períodos.',
         'bpd_desc': 'Distribución de clientes nuevos e ingresos por canal de adquisición.',
         'bpa_merge_nome': 'Adquisición por canal',
         'cohort_eixo_total': '{m} (k)',
         'cohort_eixo_medio': '{m} medio por cliente activo (R$)',
         'cohort_eixo_acum': '{m} medio acumulado por cliente (R$)',
         'cohort_variant_avg': 'Media por cliente',
         'cohort_variant_avg_hint': 'Total de la cohorte dividido por los clientes activos '
                                    'de ese mes.',
         'cohort_metric_deposits': 'Pagos',
         'cohort_metric_netcash': 'Ingresos netos'},
        "en":
        {'vertical_nome': 'E-commerce',
         'unidade_cliente': 'customer',
         'unidade_cliente_plural': 'customers',
         'vertical_a': 'Marketplace (3P)',
         'vertical_b': 'Own store (1P)',
         'vertical_par': 'marketplace + own store',
         'ggr': 'Revenue',
         'ggr_hint': 'Marketplace commission (3P) + gross margin of the own store (1P).',
         'ngr': 'Contribution margin',
         'ngr_hint': 'Revenue minus coupons and discounts granted.',
         'turnover': 'GMV',
         'turnover_hint': 'Total value transacted in orders.',
         'margem': 'Take rate',
         'margem_hint': 'Revenue / GMV.',
         'hold': 'Net margin',
         'hold_hint': 'Contribution margin / Revenue.',
         'depositos': 'Approved payments',
         'depositos_hint': 'Only transactions with Status = Completed.',
         'saques': 'Refunds',
         'saques_hint': 'Only transactions with Status = Completed.',
         'netcash': 'Net revenue',
         'netcash_hint': 'Approved payments minus refunds.',
         'ftds': 'New customers',
         'ftds_hint': 'Customers with their first purchase in the period.',
         'registros': 'Sign-ups',
         'registros_hint': 'Accounts created in the period.',
         'uap': 'Active customers',
         'uap_hint': 'Unique customers with an order in the marketplace or the own store.',
         'arpu': 'Revenue per customer',
         'arpu_hint': 'Revenue divided by active customers.',
         'itens': 'Items',
         'donut_vertical': 'Revenue by operation',
         'donut_vertical_desc': 'Marketplace (3P) against own store (1P) in the period.',
         'donut_provedor': 'Revenue by seller',
         'donut_provedor_desc': 'Top 12 sellers by revenue; the rest add up under “Others”.',
         'donut_canal': 'Acquisition by channel',
         'donut_canal_desc': 'Customer sign-up channel; the metrics are from the selected '
                             'period.',
         'nota_ngr_zero': 'The own store margin comes in as zero in this database — '
                          '“Contribution margin” and “Net margin” reflect the marketplace '
                          'only.',
         'overview_desc': 'Revenue, margin, payments and acquisition for the period, '
                          'compared against the previous window of the same length.',
         'retention_desc': 'Cohort retention by Revenue, GMV, Payments and Net revenue.',
         'report_master_desc': 'Executive spreadsheet: 5 tabs (Operational Overview, '
                               'Marketplace, Own store, CRM and Acquisition) with the period '
                               'metrics. 76 queries.',
         'monitoring_desc': 'Performance by partnership manager, comparing two periods.',
         'bpa_desc': 'Acquisition: new customers, payments and revenue by channel, two '
                     'periods.',
         'bpd_desc': 'Distribution of new customers and revenue by acquisition channel.',
         'bpa_merge_nome': 'Acquisition by channel',
         'cohort_eixo_total': '{m} (k)',
         'cohort_eixo_medio': '{m} per active customer (R$)',
         'cohort_eixo_acum': 'Cumulative {m} per customer (R$)',
         'cohort_variant_avg': 'Average per customer',
         'cohort_variant_avg_hint': 'Cohort total divided by the customers active that '
                                    'month.',
         'cohort_metric_deposits': 'Payments',
         'cohort_metric_netcash': 'Net revenue'},
    },
}
